2023-04-18 18:11:53,855 ERROR: Exception on /user/Susan [GET] [in /Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/main/routes.py", line 73, in user
    return render_template('main/user.html', user=user, posts=posts.items,
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/templates/main/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
2023-04-18 18:12:59,270 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:71]
2023-04-18 18:13:05,919 ERROR: Exception on /user/Susan [GET] [in /Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/main/routes.py", line 73, in user
    return render_template('main/user.html', user=user, posts=posts.items,
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/templates/main/user.html", line 1, in top-level template code
    {% extends "main/base.html" %}
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/templates/main/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/templates/main/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/zhuoyangmeng/Desktop/Microblog/app/templates/main/user.html", line 17, in block 'app_content'
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/zhuoyangmeng/Desktop/Microblog/myblog/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2023-05-01 20:25:25,723 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:76]
2023-05-01 20:25:50,239 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:76]
2023-05-01 22:30:16,326 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:76]
2023-05-01 22:30:42,902 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:76]
2023-05-03 18:15:16,651 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:79]
2023-05-03 18:15:24,223 INFO: Microblog startup [in /Users/zhuoyangmeng/Desktop/Microblog/app/__init__.py:79]
